### ISSUE TITLE
Easy Digital Downloads Checkout Issues

### ISSUE THREAD

**Issue by Basilakis** [gijo-varghese/flying-pages#1]
Hello,

Installing the plugin with Easy Digital Downloads creat issues with the cart page. The end result is that the cart shows as empty and no payment can be procced.

**Comment by gijo-varghese** [comment]
@Basilakis have you added the keywords like "cart", "checkout" for related pages in 'ignore list?'

**Comment by gijo-varghese** [comment]
@Basilakis also, adding "?" to the ignore list should fix most of the issues. I just tested it with an EDD site and it's working fine

**Comment by gijo-varghese** [comment]
@Basilakis I'm closing the issue since there is no update
