### ISSUE TITLE
Not working on Firefox or Safari, but Chrome is OK

### ISSUE THREAD

**Issue by adrianvanburen** [gijo-varghese/flying-pages#14]
This plugin does not work on Firefox or Safari, but does work for Chrome. Please see my website as an example:

https://www.lyka.stream/

<img width="1260" alt="safari" src="https://user-images.githubusercontent.com/38585777/171581042-a8147d21-6964-47dc-a115-5dcd4d6c63a8.png">
<img width="1175" alt="chrome" src="https://user-images.githubusercontent.com/38585777/171581078-34295c5b-fdb2-43f5-b713-fdc39d5513aa.png">
<img width="977" alt="firefox" src="https://user-images.githubusercontent.com/38585777/171581083-58f0f3c4-6854-48e2-bbea-4389bb395dd1.png">

As you see, Chrome is the only one that prefetches. Do you know why this is? Is it possible to bring support to these other two browsers?

**Comment by gijo-varghese** [comment]
@adrianvanburen Preload is not supported in all browsers. You can check the support here: https://caniuse.com/link-rel-preload.

Chromium-based browsers are guaranteed to work.

**Comment by adrianvanburen** [comment]
Both Firefox and Safari are supported, since 2021 & 2018. I'm running the latest version of the browsers, so I have compatibility.

I'm using Firefox version 101
<img width="698" alt="Capture d’écran 2022-06-02 à 14 38 27" src="https://user-images.githubusercontent.com/38585777/171621215-1da81b07-a8ec-4eff-b4ef-f205e43bb780.png">

**Comment by gijo-varghese** [comment]
@adrianvanburen sorry, it's not preload, it's prefetch: https://caniuse.com/link-rel-prefetch

Safari is not supported. I think Firebox has disabled it by default. You might need to enable it.

**Comment by adrianvanburen** [comment]
@gijo-varghese Thank you for the guidance. I confirm that is correct.

For those with the similar complaint, this is how to change the setting in Firefox:

1. Open a tab, go to "about:config"
2. Click beyond the warnings
3. Search for the setting "network.prefetch-next" and set it to "true"

This plugin does now, indeed work, with this setting activated. Proof:
<img width="1440" alt="Capture d’écran 2022-06-04 à 00 32 29" src="https://user-images.githubusercontent.com/38585777/171956195-fb36726a-52e4-4c08-b0dc-845383107b08.png">

**Comment by gijo-varghese** [comment]
@adrianvanburen great, thanks!
