### ISSUE TITLE
Flying SCRIPTS ??

### ISSUE THREAD

**Issue by podporujeme** [gijo-varghese/flying-pages#17]
Hello, am sorry but i cant find repository for Flying Scripts, 

so can i try here? pls

Does it work for me? When the google speed test for "www-embed-player.js" reports the same "ms" as before the test.

The screenshot of my "settings in administration" is the second one, at the end.

My next question is whether the plugin can deal with the google message: "Some third-party resources can be lazy loaded with a facade"

google speed test:

![sdfsf](https://github.com/gijo-varghese/flying-pages/assets/141672673/c1bfbdc6-dbbe-418d-aee3-282d48598f42)

my settings in admin:

![dfdf](https://github.com/gijo-varghese/flying-pages/assets/141672673/682ef691-c8d5-4ce9-a12b-a8a524737bc8)

**Comment by gijo-varghese** [comment]
YouTube embed JS is probably from iFrame. In that case, you need to lazy load iFrames. Flying Scripts can't do that. You need [FlyingPress](https://flyingpress.com).
