### ISSUE TITLE
Warning: get_headers()   error?

### ISSUE THREAD

**Issue by uborkh** [gijo-varghese/flying-pages#5]
Hello
Warning: get_headers(): https:// wrapper is disabled in the server configuration by allow_url_fopen=0 in /home/fz43556/somedomain/www/wp-content/plugins/flying-pages/settings/compatibility.php on line 6

Warning: get_headers(): This function may only be used against URLs in /home/fz43556/somedomain/www/wp-content/plugins/flying-pages/settings/compatibility.php on line 6

What does it means? cant see plugin working..
Thank you

**Comment by gijo-varghese** [comment]
@uborkh you need to contact your hosting provider to enable `allow_url_fopen`
