### ISSUE TITLE
Question: Can pre-fetch be called up with onClick event instead of a href="url" ?

### ISSUE THREAD

**Issue by inglesuniversal** [gijo-varghese/flying-pages#6]
Can I use a DIV with onclick="requestWebpage()"> <img bla bla bla> </div>

Thanks and COOL idea!

**Comment by gijo-varghese** [comment]
@inglesuniversal That's not possible with Flying Pages. You can write some custom code to create a `<link rel="ploread" ....>` on the onclick function.
